# this file contains example config data
auth:
  type: internal
  users:
    - username: example_rw
      password: example_password
      permission: RW
      zip_encryption_key: example_zip_key
      zip_timeout: 60 # unit: second
    - username: example_r
      password: example_read_password
      permission: R

config_databases:
  local:
    ip: 127.0.0.1
    port: 5432
    database_name: postgres
    username: postgres
    password: postgres

task_status_display_name:
  1: running
  2: success
  3: fail
  4: cancel

file_access_point_smb_external:
  nas:
    host: 192.168.0.7
    username: example_username
    password: example_password
    share: /example_share

file_access_point_smb_internal:
  file_access_point_smb_internal_example:
    name: smb/internal-file-access-point-example
    file_access_point_smb_external_info:
      name: nas
    path_root: /file/
    metadata:
      purpose: example